{
  IllegalArgumentException expected=new IllegalArgumentException("thrown by mock");
  when(mock.add("throw")).thenThrow(expected);
  try {
    mock.add("throw");
    fail();
  }
 catch (  IllegalArgumentException e) {
    assertEquals(expected,e);
  }
}
