{
  mock.twoArgumentMethod(1,2);
  control.setDefaultVoidCallable();
  mock.twoArgumentMethod(1,1);
  RuntimeException expected=new RuntimeException();
  control.setThrowable(expected);
  control.replay();
  mock.twoArgumentMethod(2,1);
  mock.twoArgumentMethod(1,2);
  mock.twoArgumentMethod(3,7);
  try {
    mock.twoArgumentMethod(1,1);
    fail("RuntimeException expected");
  }
 catch (  RuntimeException actual) {
    assertSame(expected,actual);
  }
}
