{
  stub(mock.add("ExceptionOne")).andThrows(new ExceptionOne());
  try {
    addObjectToMockedList("ExceptionOne");
    fail();
  }
 catch (  ExceptionOne e) {
    assertThat(e,firstMethodOnStackEqualsTo("addObjectToMockedList"));
  }
}
