{
  mock.twoArgumentMethod(1,2);
  control.setVoidCallable();
  mock.twoArgumentMethod(1,1);
  control.setVoidCallable();
  RuntimeException expected=new RuntimeException();
  control.setDefaultThrowable(expected);
  control.replay();
  mock.twoArgumentMethod(1,2);
  mock.twoArgumentMethod(1,1);
  try {
    mock.twoArgumentMethod(2,1);
    fail("RuntimeException expected");
  }
 catch (  RuntimeException actual) {
    assertSame(expected,actual);
  }
}
