{
  control.expectAndThrow(mock.longReturningMethod(4),EXCEPTION);
  control.replay();
  try {
    mock.longReturningMethod(4);
    fail();
  }
 catch (  RuntimeException exception) {
    assertSame(EXCEPTION,exception);
  }
  control.verify();
}
