{
  Error error=new Error();
  when(mock.add("quake")).thenThrow(error);
  try {
    mock.add("quake");
    fail();
  }
 catch (  Error e) {
    assertEquals(error,e);
  }
}
