{
  return new MockitoException(join("Cannot stub with null throwable!"));
}
