{
  try {
    validator.validate(new ThrowsException(null),new InvocationBuilder().toInvocation());
    fail();
  }
 catch (  MockitoException e) {
  }
}
