{
  throw new MockitoException(join("Checked exception is invalid for this method","Invalid: " + t));
}
